# -*- coding: utf-8 -*-
"""agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYuQR75PvCjpiL0OW3MBXEp6DYoqu0C7
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any

@dataclass
class AgentState:
    user_query: str
    plan: List[str] = field(default_factory=list)
    research: List[str] = field(default_factory=list)
    knowledge: List[str] = field(default_factory=list)
    reasoning: str = ""
    answer: str = ""
    critique: str = ""
    confidence: float = 0.0
    approved: bool = False
    retry_count: int = 0
    errors: List[str] = field(default_factory=list)

class BaseAgent:

    def __init__(self, name: str):
        self.name = name

    def log(self, message: str):

        print(f"[{self.name}] {message}")

class PlannerAgent(BaseAgent):

    def __init__(self):
        super().__init__("PLANNER")

    def run(self, state: AgentState):

        self.log("Understanding the task...")

        state.plan = [
            "Understand the user's question",
            "Find relevant information",
            "Retrieve internal knowledge",
            "Analyze the information",
            "Generate an answer",
            "Verify the answer"
        ]

        return state

class ResearchAgent(BaseAgent):

    def __init__(self):
        super().__init__("RESEARCHER")

    def run(self, state: AgentState):

        self.log("Collecting external evidence...")

        state.research = [
            f"Research required for query: {state.user_query}"
        ]

        return state

class KnowledgeAgent(BaseAgent):

    def __init__(self):
        super().__init__("KNOWLEDGE")

    def run(self, state: AgentState):

        self.log("Searching internal knowledge...")
        state.knowledge = [
            f"Internal knowledge lookup for: {state.user_query}"
        ]

        return state

class ReasoningAgent(BaseAgent):

    def __init__(self):
        super().__init__("REASONER")

    def run(self, state: AgentState):

        self.log("Analyzing available information...")

        evidence_count = (
            len(state.research)
            + len(state.knowledge)
        )

        state.reasoning = (
            f"The system analyzed {evidence_count} "
            f"evidence items related to the query."
        )

        state.answer = (
            f"Based on the available information, "
            f"the query '{state.user_query}' "
            f"has been analyzed."
        )

        return state

class CriticAgent(BaseAgent):

    def __init__(self):
        super().__init__("CRITIC")

    def run(self, state: AgentState):

        self.log("Verifying the generated answer...")

        problems = []

        # Check 1
        if not state.answer:
            problems.append("Answer is empty.")

        # Check 2
        if not state.research:
            problems.append("No research evidence.")

        # Check 3
        if not state.knowledge:
            problems.append("No internal knowledge.")

        # Check 4
        if not state.reasoning:
            problems.append("No reasoning generated.")

        if problems:

            state.approved = False
            state.confidence = 0.30

            state.critique = "; ".join(problems)

            self.log(" Answer rejected.")

        else:

            state.approved = True
            state.confidence = 0.90

            state.critique = "No structural problems detected."

            self.log(" Answer approved.")

        return state

class Orchestrator:

    MAX_RETRIES = 2

    def __init__(self):

        self.planner = PlannerAgent()
        self.researcher = ResearchAgent()
        self.knowledge = KnowledgeAgent()
        self.reasoner = ReasoningAgent()
        self.critic = CriticAgent()


    # MAIN PIPELINE


    def run(self, query: str):

        state = AgentState(
            user_query=query
        )

        print("\n" + "=" * 60)
        print("🚀 MULTI-AGENT SYSTEM STARTED")
        print("=" * 60)

        # ----------------------------------------------------
        # STEP 1 — PLANNING
        # ----------------------------------------------------

        state = self.planner.run(state)


        # RETRY LOOP

        while state.retry_count <= self.MAX_RETRIES:

            print(
                f"\n--- Attempt "
                f"{state.retry_count + 1} ---"
            )

            # ------------------------------------------------
            # STEP 2 — RESEARCH
            # ------------------------------------------------

            state = self.researcher.run(state)


            # STEP 3 — KNOWLEDGE

            state = self.knowledge.run(state)


            # STEP 4 — REASONING


            state = self.reasoner.run(state)




            state = self.critic.run(state)


            # DECISION


            if state.approved:

                break

            state.retry_count += 1

            if state.retry_count <= self.MAX_RETRIES:

                print(
                    "🔄 Replanning because verification failed..."
                )

                state = self.planner.run(state)

        # FINAL OUTPUT

        print("\n" + "=" * 60)

        if state.approved:

            print(" FINAL ANSWER APPROVED")
            print("=" * 60)

            print("\nAnswer:")
            print(state.answer)

            print(
                f"\nConfidence: "
                f"{state.confidence:.2f}"
            )

            print(
                f"Retries: "
                f"{state.retry_count}"
            )

        else:

            print(" SYSTEM COULD NOT VERIFY ANSWER")
            print("=" * 60)

            print(
                "\nReason:",
                state.critique
            )

        return state

def main():

    system = Orchestrator()

    print("\n Phase 2 Multi-Agent AI")

    query = input(
        "\n Enter your question: "
    ).strip()

    if not query:

        print(" Query cannot be empty.")
        return

    system.run(query)

if __name__ == "__main__":

    main()